set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-terminal "tmux-256color"
set -g status-right "#{pane_title}"
set -g status-style bg=default
set -g status-position top 
set -s escape-time 0
set -g automatic-rename on
set -g allow-rename on
set -g set-titles on
set -g default-shell /opt/homebrew/bin/fish
set -g base-index 1
#   #S = tmux session name
#   #I = tmux window index
#   #W = tmux window name
#   #P = current pane index
#   #h = hostname (short form)
#   #H = hostname (full form)
#   #T = pane title (often the command running in it)
set -g set-titles-string '#h::#W'
set-option -g history-limit 10000

set -g mode-keys vi
set -g mouse on

# Force UTF-8 support (needed for emoji rendering over SSH)
set -gq utf8 on
set -gq status-utf8 on

# Enable focus events for neovim
set -g focus-events on

# Setup vi-style copy/paste for macOS
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi r send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind p run "pbpaste | tmux load-buffer - ; tmux paste-buffer"
unbind-key C-b
set -g prefix C-a
bind C-a send-prefix


bind j select-pane -L
bind k select-pane -D
bind l select-pane -U
bind ';' select-pane -R

bind u last-window 

bind-key z resize-pane -L 10
bind-key x resize-pane -D 10
bind-key c resize-pane -U 11
bind-key v resize-pane -R 10

bind c new-window -c "#{pane_current_path}"
bind-key q kill-pane
