# Lumon (Omarchy 4)
[colors]
background=16242dfa
selection=243d56fa
border=f2fcfffa
text=d6e2eefa
prompt=d6e2eefa
input=d6e2eefa
match=8bc9ebfa
selection-match=8bc9ebfa
selection-text=d6e2eefa

[main]
lines=3
line-height=32
width=22
font=JetBrainsMono Nerd Font:size=11
fields=name,generic,comment,categories,keywords
match-mode=fuzzy
filter-desktop=yes
show-actions=no
exit-on-keyboard-focus-loss=no
terminal=alacritty -e
icons-enabled=true
hide-prompt=false
horizontal-pad=6
vertical-pad=4
