# Reference for all options: man 5 foot.ini

font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes

[mouse]
hide-when-typing=yes

[cursor]
color = 16242d f2fcff

# Lumon (Omarchy 4)
[colors]
foreground = d6e2ee
background = 16242d
selection-foreground = d6e2ee
selection-background = 243d56

regular0 = 16242d
regular1 = 4d86b0
regular2 = 5e95bc
regular3 = 6fa4c9
regular4 = 6fb8e3
regular5 = 8bc9eb
regular6 = b4e4f6
regular7 = d6e2ee

bright0 = 304860
bright1 = 73a6cb
bright2 = 86b7d8
bright3 = 9dcae5
bright4 = f2fcff
bright5 = b1d8ee
bright6 = d1eef8
bright7 = f2fcff
