[[language]]
name = "fish"
language-servers = [ "fish-lsp" ]

[language-server.fish-lsp]
command = "fish-lsp"
args= ["start"]
environment = { "fish_lsp_show_client_popups" = "false" }

[[language]]
auto-format = true
file-types = ["ts", "tsx", "mts"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
name = "typescript"
scope = "source.typescript"

[[language]]
auto-format = true
file-types = ["js", "jsx", "mjs", "cjs"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
name = "javascript"
scope = "source.javascript"

[[language]]
auto-format = true
file-types = ["css"]
formatter = { command = "prettier", args = ["--parser", "css"] }
name = "css"
scope = "source.css"

[[language]]
auto-format = true
file-types = ["scss"]
formatter = { command = "prettier", args = ["--parser", "scss"] }
name = "scss"
scope = "source.scss"

[[language]]
auto-format = true
file-types = ["less"]
formatter = { command = "prettier", args = ["--parser", "less"] }
name = "less"
scope = "source.less"

[[language]]
auto-format = true
file-types = ["html"]
formatter = { command = "prettier", args = ["--parser", "html"] }
name = "html"
scope = "source.html"

[[language]]
auto-format = true
file-types = ["json"]
formatter = { command = "prettier", args = ["--parser", "json"] }
name = "json"
scope = "source.json"

[[language]]
auto-format = true
file-types = ["yaml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
name = "yaml"
scope = "source.yaml"

[[language]]
auto-format = true
file-types = ["md"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
name = "markdown"
scope = "source.markdown"

# Configurazione Volar (Vue Language Server)
[language-server.volar]
command = "vue-language-server"
args = ["--stdio"]

[language-server.volar.config]
vue = { hybridMode = false }
typescript = { tsdk = "node_modules/typescript/lib" }

# Configurazione Vue
[[language]]
name = "vue"
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
roots = ["package.json", ".git"]
language-servers = ["volar"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
