set -g history-limit 50000
set -sg repeat-time 600
set -sg escape-time 1
setw -g mouse on
setw -gq utf8 on

# Enable focus events for terminal
set -g focus-events on

# Setup vi-style copy/paste
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi r send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind p run "pbpaste | tmux load-buffer - ; tmux paste-buffer"

# Enable default terminal colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
bind j select-pane -L
bind k select-pane -D
bind l select-pane -U
bind ';' select-pane -R
bind -r C-h select-window -t+:-
bind -r C-l select-window -t+:+

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
