# Lumon (Omarchy 4)
[colors.primary]
background = "#16242d"
foreground = "#d6e2ee"
dim_foreground = "#4d86b0"

[colors.cursor]
text = "#16242d"
cursor = "#f2fcff"

[colors.vi_mode_cursor]
text = "#16242d"
cursor = "#f2fcff"

[colors.selection]
text = "CellForeground"
background = "#243d56"

[colors.search.matches]
foreground = "CellBackground"
background = "#6fa4c9"

[colors.normal]
black = "#16242d"
red = "#4d86b0"
green = "#5e95bc"
yellow = "#6fa4c9"
blue = "#6fb8e3"
magenta = "#8bc9eb"
cyan = "#b4e4f6"
white = "#d6e2ee"

[colors.bright]
black = "#304860"
red = "#73a6cb"
green = "#86b7d8"
yellow = "#9dcae5"
blue = "#f2fcff"
magenta = "#b1d8ee"
cyan = "#d1eef8"
white = "#f2fcff"

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/fish"

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
y = 2

[window.padding]
x = 2
y = 2

[keyboard] 
#https://alacritty.org/config-alacritty-bindings.html
bindings = [
{ key = "Tab", mods = "Control", action = "SelectNextTab" },
{ key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
# disable the macOS close-window shortcut
{ key = "w", mods= "Command", action = "None"},
]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
